image: continuumio/miniconda3:latest
before_script:
  - conda env create -f environment.yml
  - source activate cmelab
  - python -m pip install pytest pytest-cov
tests:
  stage: test and report to codecov
  script:
    - python -m pytest --cov=./ --cov-report=xml
    - bash <(curl -s https://codecov.io/bash)